### ISSUE TITLE
Add vscode tasks

### ISSUE THREAD

**Issue by andresgarciaf** [MaaniBeigy/dash-boilerplate#4]
## 🚀 Feature Request

Can tasks be added to the project?

## 🔈 Motivation

This will facilitate certain shortcuts for initial development.

## 🛰 Sample tasks.

`{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
      {
          "label": "build docker",
          "type": "shell",
          "command": "docker-compose up -d --build"
      },
      {
        "label": "stop docker",
        "type": "shell",
        "command": "docker-compose -f docker-compose.yml down -v"
    },
      {
        "label": "rename env",
        "type": "shell",
        "command": "cp .env.${input:env_type}.example .env.${input:env_type}"
    }
  ],
  "inputs": [
      {
          "id": "env_type",
          "description": "Input 'dev' for development or 'prod' for production.",
          "default": "",
          "type": "promptString"
      },
  ]
}
`

**Comment by MaaniBeigy** [comment]
@jgarciaf106 
It will be a great enhancement,
Thanks
